### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by jiayou50** [LeagueOfPoro/PoroLobby#2]
Likely after the new s13 changes.

**Comment by jiayou50** [comment]
https://github.com/sousa-andre/lcu-driver/issues/28 is the fix

**Comment by ChuniMegu** [comment]
> [sousa-andre/lcu-driver#28](https://github.com/sousa-andre/lcu-driver/issues/28) is the fix

could you please give me a step to tep guide on how to apply it, the only python ik is in my pants T_T

**Comment by LeagueOfPoro** [comment]
I'm working on a fix. Using the latest lcu-driver throws some weird errors

**Comment by LeagueOfPoro** [comment]
I completely rewrote the tool and got rid of the lcu-driver. It should work now.
