### ISSUE TITLE
Bug in parsing of token

### ISSUE THREAD

**Issue by bogglez** [LeagueOfPoro/PoroLobby#3]
https://github.com/LeagueOfPoro/PoroLobby/blob/a0fd835679378c86d33a77d68092b37363e861d9/ConnectionManager.py#L43

Same bug as in lcu-driver: the split must be limited to one time only. It’s possible for the value to contain equal signs (padding in base64). Sometimes the token will contain them and requests will fail.

**Comment by LeagueOfPoro** [comment]
Thanks, [fixed](https://github.com/LeagueOfPoro/PoroLobby/commit/d2abffad34416252a3bf3f6c92849b86c7ca5503)
